import type { Portfolio, Service, TeamMember, Testimonial, ContactMessage, DashboardStats } from "./types"

export const portfolioData: Portfolio[] = [
  {
    id: "1",
    title: "Software Engineer Portfolio",
    description:
      "A comprehensive software engineering portfolio showcasing full-stack development skills, system design expertise, and problem-solving capabilities. Features clean code architecture, scalable solutions, and modern development practices with extensive documentation and testing coverage.",
    shortDescription: "Complete software engineering showcase with system design expertise",
    image: "/images/p1.png",
    category: "Software Engineering",
    tags: ["Java", "Python", "System Design", "Algorithms"],
    liveUrl: "https://v0-bhuvana-portfolio-clone.vercel.app/",
    githubUrl: "https://github.com/example/software-engineer",
    slug: "software-engineer-portfolio",
    technologies: ["Java", "Python", "Spring Boot", "PostgreSQL", "Docker", "AWS"],
    featured: true,
    createdAt: "2024-01-15",
  },
  {
    id: "se-2",
    title: "Enterprise Java Developer Portfolio",
    description:
      "Specialized Java enterprise application development with Spring ecosystem, microservices architecture, and cloud deployment strategies.",
    shortDescription: "Enterprise Java development with Spring and microservices",
    image: "/images/p2.png",
    category: "Software Engineering",
    tags: ["Java", "Spring Boot", "Microservices", "Kubernetes"],
    liveUrl: "https://v0-modern-portfolio-website-phi-ten.vercel.app/",
    githubUrl: "https://github.com/example/java-enterprise",
    slug: "enterprise-java-developer-portfolio",
    technologies: ["Java", "Spring Boot", "Spring Cloud", "Kubernetes", "Redis", "MySQL"],
    featured: false,
    createdAt: "2024-01-20",
  },
  {
    id: "se-3",
    title: "Python Backend Engineer Portfolio",
    description: "Backend engineering expertise with Python, Django, FastAPI, and modern API development practices.",
    shortDescription: "Python backend development with Django and FastAPI",
    image: "/images/p3.png",
    category: "Software Engineering",
    tags: ["Python", "Django", "FastAPI", "PostgreSQL"],
    liveUrl: "https://v0-modern-portfolio-design-seven-vert.vercel.app/",
    githubUrl: "https://github.com/example/python-backend",
    slug: "python-backend-engineer-portfolio",
    technologies: ["Python", "Django", "FastAPI", "PostgreSQL", "Redis", "Celery"],
    featured: false,
    createdAt: "2024-01-25",
  },
  {
    id: "se-4",
    title: "C++ Systems Developer Portfolio",
    description:
      "High-performance systems programming with C++, focusing on optimization, memory management, and concurrent programming.",
    shortDescription: "C++ systems programming with performance optimization",
    image: "/images/p4.png",
    category: "Software Engineering",
    tags: ["C++", "Systems Programming", "Performance", "Concurrency"],
    liveUrl: "https://v0-pr-43-sde.vercel.app/",
    githubUrl: "https://github.com/example/cpp-systems",
    slug: "cpp-systems-developer-portfolio",
    technologies: ["C++", "CMake", "Boost", "Linux", "GDB", "Valgrind"],
    featured: false,
    createdAt: "2024-02-01",
  },
  {
    id: "se-5",
    title: "Go Microservices Developer Portfolio",
    description:
      "Microservices architecture development using Go, with focus on scalability, performance, and cloud-native solutions.",
    shortDescription: "Go microservices development with cloud-native architecture",
    image: "/images/p5.png",
    category: "Software Engineering",
    tags: ["Go", "Microservices", "Docker", "Kubernetes"],
    liveUrl: "https://v0-replicate-sde-ui.vercel.app/",
    githubUrl: "https://github.com/example/go-microservices",
    slug: "go-microservices-developer-portfolio",
    technologies: ["Go", "Docker", "Kubernetes", "gRPC", "MongoDB", "Prometheus"],
    featured: false,
    createdAt: "2024-02-05",
  },
  {
    id: "se-6",
    title: "Rust Systems Engineer Portfolio",
    description:
      "Systems-level programming with Rust, emphasizing memory safety, performance, and concurrent programming patterns.",
    shortDescription: "Rust systems engineering with memory safety focus",
    image: "/images/p6.png",
    category: "Software Engineering",
    tags: ["Rust", "Systems", "Memory Safety", "Performance"],
    liveUrl: "https://v0-devops-portfolio-design-three.vercel.app/",
    githubUrl: "https://github.com/example/rust-systems",
    slug: "rust-systems-engineer-portfolio",
    technologies: ["Rust", "Tokio", "Serde", "Diesel", "WebAssembly", "Cargo"],
    featured: false,
    createdAt: "2024-02-10",
  },
  {
    id: "se-7",
    title: "Node.js Backend Architect Portfolio",
    description:
      "Backend architecture design with Node.js, Express, and modern JavaScript/TypeScript development practices.",
    shortDescription: "Node.js backend architecture with TypeScript",
    image: "/images/p7.png",
    category: "Software Engineering",
    tags: ["Node.js", "TypeScript", "Express", "Architecture"],
    liveUrl: "https://v0-jonny-bairstow-portfolio.vercel.app/",
    githubUrl: "https://github.com/example/nodejs-architect",
    slug: "nodejs-backend-architect-portfolio",
    technologies: ["Node.js", "TypeScript", "Express", "MongoDB", "Jest", "Docker"],
    featured: false,
    createdAt: "2024-02-15",
  },
  {
    id: "se-8",
    title: "Scala Functional Programming Portfolio",
    description: "Functional programming expertise with Scala, Akka, and reactive systems development.",
    shortDescription: "Scala functional programming with reactive systems",
    image: "/images/p8.png",
    category: "Software Engineering",
    tags: ["Scala", "Functional Programming", "Akka", "Reactive"],
    liveUrl: "https://v0-sde-portfolio-design-sooty.vercel.app/",
    githubUrl: "https://github.com/example/scala-functional",
    slug: "scala-functional-programming-portfolio",
    technologies: ["Scala", "Akka", "Play Framework", "Cats", "ScalaTest", "SBT"],
    featured: false,
    createdAt: "2024-02-20",
  },
  {
    id: "se-9",
    title: "Ruby on Rails Developer Portfolio",
    description: "Full-stack web development with Ruby on Rails, focusing on rapid prototyping and agile development.",
    shortDescription: "Ruby on Rails development with agile practices",
    image: "/images/p9.png",
    category: "Software Engineering",
    tags: ["Ruby", "Rails", "MVC", "Agile"],
    liveUrl: "https://v0-software-engineer-portfolio-three-phi.vercel.app/",
    githubUrl: "https://github.com/example/rails-developer",
    slug: "ruby-on-rails-developer-portfolio",
    technologies: ["Ruby", "Rails", "PostgreSQL", "RSpec", "Sidekiq", "Heroku"],
    featured: false,
    createdAt: "2024-02-25",
  },
  {
    id: "se-10",
    title: "PHP Laravel Developer Portfolio",
    description: "Modern PHP development with Laravel framework, emphasizing clean code and MVC architecture.",
    shortDescription: "PHP Laravel development with modern practices",
    image: "/images/p10.png",
    category: "Software Engineering",
    tags: ["PHP", "Laravel", "MVC", "Eloquent"],
    liveUrl: "https://v0-test-engineer-portfolio.vercel.app/",
    githubUrl: "https://github.com/example/laravel-developer",
    slug: "php-laravel-developer-portfolio",
    technologies: ["PHP", "Laravel", "MySQL", "PHPUnit", "Composer", "Artisan"],
    featured: false,
    createdAt: "2024-03-01",
  },
  {
    id: "se-11",
    title: "Kotlin Android Developer Portfolio",
    description:
      "Android application development with Kotlin, modern Android architecture components, and Material Design.",
    shortDescription: "Kotlin Android development with modern architecture",
    image: "/images/p11.png",
    category: "Software Engineering",
    tags: ["Kotlin", "Android", "MVVM", "Material Design"],
    liveUrl: "https://kavyas.netlify.app/",
    githubUrl: "https://github.com/example/kotlin-android",
    slug: "kotlin-android-developer-portfolio",
    technologies: ["Kotlin", "Android SDK", "Jetpack Compose", "Room", "Retrofit", "Dagger"],
    featured: false,
    createdAt: "2024-03-05",
  },
  {
    id: "se-12",
    title: "Swift iOS Developer Portfolio",
    description: "iOS application development with Swift, UIKit, SwiftUI, and modern iOS development patterns.",
    shortDescription: "Swift iOS development with UIKit and SwiftUI",
    image: "/images/p12.png",
    category: "Software Engineering",
    tags: ["Swift", "iOS", "UIKit", "SwiftUI"],
    liveUrl: "https://v0-hanben-portfolio-design.vercel.app/",
    githubUrl: "https://github.com/example/swift-ios",
    slug: "swift-ios-developer-portfolio",
    technologies: ["Swift", "UIKit", "SwiftUI", "Core Data", "Alamofire", "XCTest"],
    featured: false,
    createdAt: "2024-03-10",
  },
  {
    id: "se-13",
    title: "C# .NET Developer Portfolio",
    description: ".NET ecosystem development with C#, ASP.NET Core, and modern Microsoft technologies.",
    shortDescription: "C# .NET development with ASP.NET Core",
    image: "/images/p13.png",
    category: "Software Engineering",
    tags: ["C#", ".NET", "ASP.NET Core", "Entity Framework"],
    liveUrl: "https://v0-portfolio-design-concept-six.vercel.app/",
    githubUrl: "https://github.com/example/csharp-dotnet",
    slug: "csharp-dotnet-developer-portfolio",
    technologies: ["C#", ".NET 6", "ASP.NET Core", "Entity Framework", "SQL Server", "Azure"],
    featured: false,
    createdAt: "2024-03-15",
  },
  {
    id: "se-14",
    title: "Elixir Phoenix Developer Portfolio",
    description: "Functional programming with Elixir and Phoenix framework, focusing on fault-tolerant systems.",
    shortDescription: "Elixir Phoenix development with fault-tolerant systems",
    image: "/images/p14.png",
    category: "Software Engineering",
    tags: ["Elixir", "Phoenix", "OTP", "Fault Tolerance"],
    liveUrl: "https://v0-improve-portfolio-ui-murex.vercel.app/",
    githubUrl: "https://github.com/example/elixir-phoenix",
    slug: "elixir-phoenix-developer-portfolio",
    technologies: ["Elixir", "Phoenix", "OTP", "Ecto", "LiveView", "PostgreSQL"],
    featured: false,
    createdAt: "2024-03-20",
  },
  {
    id: "se-15",
    title: "Clojure Developer Portfolio",
    description: "Functional programming with Clojure, emphasizing immutability and concurrent programming.",
    shortDescription: "Clojure development with immutability and concurrency",
    image: "/images/p15.png",
    category: "Software Engineering",
    tags: ["Clojure", "Functional", "Immutability", "Concurrency"],
    liveUrl: "https://v0-james-walt-portfolio.vercel.app/",
    githubUrl: "https://github.com/example/clojure-developer",
    slug: "clojure-developer-portfolio",
    technologies: ["Clojure", "Leiningen", "Ring", "Compojure", "Datomic", "ClojureScript"],
    featured: false,
    createdAt: "2024-03-25",
  },
  {
    id: "se-16",
    title: "Haskell Functional Developer Portfolio",
    description: "Pure functional programming with Haskell, type safety, and mathematical programming approaches.",
    shortDescription: "Haskell functional programming with type safety",
    image: "/images/p18.png",
    category: "Software Engineering",
    tags: ["Haskell", "Pure Functional", "Type Safety", "Mathematics"],
    liveUrl: "https://v0-vara-portfolio-template.vercel.app/",
    githubUrl: "https://github.com/example/haskell-functional",
    slug: "haskell-functional-developer-portfolio",
    technologies: ["Haskell", "GHC", "Cabal", "QuickCheck", "Parsec", "Yesod"],
    featured: false,
    createdAt: "2024-03-30",
  },
  {
    id: "se-17",
    title: "Dart Flutter Developer Portfolio",
    description: "Cross-platform mobile development with Dart and Flutter, creating beautiful native interfaces.",
    shortDescription: "Dart Flutter cross-platform mobile development",
    image: "/images/p19.png",
    category: "Software Engineering",
    tags: ["Dart", "Flutter", "Cross-platform", "Mobile"],
    liveUrl: "https://richardgore.vercel.app/",
    githubUrl: "https://github.com/example/dart-flutter",
    slug: "dart-flutter-developer-portfolio",
    technologies: ["Dart", "Flutter", "Provider", "Bloc", "Firebase", "SQLite"],
    featured: false,
    createdAt: "2024-04-01",
  },
  {
    id: "se-18",
    title: "Assembly Language Developer Portfolio",
    description: "Low-level programming with Assembly language, system optimization, and embedded systems development.",
    shortDescription: "Assembly language development with system optimization",
    image: "/images/p20.png",
    category: "Software Engineering",
    tags: ["Assembly", "Low-level", "Optimization", "Embedded"],
    liveUrl: "https://v0-portfolio-website-design-theta-orcin.vercel.app/",
    githubUrl: "https://github.com/example/assembly-developer",
    slug: "assembly-language-developer-portfolio",
    technologies: ["x86 Assembly", "ARM Assembly", "NASM", "GAS", "Debuggers", "Emulators"],
    featured: false,
    createdAt: "2024-04-05",
  },
  {
    id: "se-19",
    title: "COBOL Legacy Systems Portfolio",
    description: "Mainframe and legacy systems development with COBOL, focusing on enterprise system maintenance.",
    shortDescription: "COBOL legacy systems and mainframe development",
    image: "/images/p21.png",
    category: "Software Engineering",
    tags: ["COBOL", "Mainframe", "Legacy Systems", "Enterprise"],
    liveUrl: "https://v0-portfolio-design-guide.vercel.app/",
    githubUrl: "https://github.com/example/cobol-legacy",
    slug: "cobol-legacy-systems-portfolio",
    technologies: ["COBOL", "JCL", "CICS", "DB2", "VSAM", "TSO/ISPF"],
    featured: false,
    createdAt: "2024-04-10",
  },
  {
    id: "se-20",
    title: "Perl Systems Administrator Portfolio",
    description: "System administration and automation with Perl, focusing on text processing and system scripting.",
    shortDescription: "Perl system administration and scripting",
    image: "/images/p22.png",
    category: "Software Engineering",
    tags: ["Perl", "System Admin", "Automation", "Scripting"],
    liveUrl: "https://v0-portfolio-with-images.vercel.app/",
    githubUrl: "https://github.com/example/perl-sysadmin",
    slug: "perl-systems-administrator-portfolio",
    technologies: ["Perl", "CPAN", "DBI", "Mojolicious", "Regular Expressions", "Unix/Linux"],
    featured: false,
    createdAt: "2024-04-15",
  },
  {
    id: "se-21",
    title: "R Statistical Computing Portfolio",
    description: "Statistical computing and data analysis with R, focusing on research and academic applications.",
    shortDescription: "R statistical computing and data analysis",
    image: "/images/p23.png",
    category: "Software Engineering",
    tags: ["R", "Statistics", "Data Analysis", "Research"],
    liveUrl: "https://v0-bryden-carse-portfolio.vercel.app/",
    githubUrl: "https://github.com/example/r-statistical",
    slug: "r-statistical-computing-portfolio",
    technologies: ["R", "RStudio", "Shiny", "ggplot2", "dplyr", "tidyverse"],
    featured: false,
    createdAt: "2024-04-20",
  },
  {
    id: "se-22",
    title: "MATLAB Engineering Portfolio",
    description: "Engineering and scientific computing with MATLAB, focusing on numerical analysis and simulation.",
    shortDescription: "MATLAB engineering and scientific computing",
    image: "/images/p24.png",
    category: "Software Engineering",
    tags: ["MATLAB", "Engineering", "Simulation", "Numerical Analysis"],
    liveUrl: "https://v0-portfolio-with-3-d-animation.vercel.app/",
    githubUrl: "https://github.com/example/matlab-engineering",
    slug: "matlab-engineering-portfolio",
    technologies: ["MATLAB", "Simulink", "Signal Processing", "Control Systems", "Image Processing", "Statistics"],
    featured: false,
    createdAt: "2024-04-25",
  },
  {
    id: "se-23",
    title: "Fortran Scientific Computing Portfolio",
    description: "High-performance scientific computing with Fortran, focusing on numerical methods and HPC.",
    shortDescription: "Fortran scientific computing and HPC",
    image: "/images/p25.png",
    category: "Software Engineering",
    tags: ["Fortran", "Scientific Computing", "HPC", "Numerical Methods"],
    liveUrl: "https://v0-dark-theme-portfolio-five.vercel.app/",
    githubUrl: "https://github.com/example/fortran-scientific",
    slug: "fortran-scientific-computing-portfolio",
    technologies: ["Fortran", "OpenMP", "MPI", "LAPACK", "BLAS", "GNU Fortran"],
    featured: false,
    createdAt: "2024-04-30",
  },
  {
    id: "se-24",
    title: "Julia High-Performance Computing Portfolio",
    description:
      "High-performance computing with Julia, combining ease of use with performance for scientific applications.",
    shortDescription: "Julia high-performance computing for scientific applications",
    image: "/images/p26.png",
    category: "Software Engineering",
    tags: ["Julia", "HPC", "Scientific Computing", "Performance"],
    liveUrl: "https://v0-portfolio-clone-request-green.vercel.app/",
    githubUrl: "https://github.com/example/julia-hpc",
    slug: "julia-high-performance-computing-portfolio",
    technologies: ["Julia", "Pkg", "Plots.jl", "DataFrames.jl", "Flux.jl", "DifferentialEquations.jl"],
    featured: false,
    createdAt: "2024-05-01",
  },
  {
    id: "se-25",
    title: "Lua Embedded Systems Portfolio",
    description: "Embedded systems development with Lua, focusing on lightweight scripting and game development.",
    shortDescription: "Lua embedded systems and scripting",
    image: "/images/p27.png",
    category: "Software Engineering",
    tags: ["Lua", "Embedded", "Scripting", "Game Development"],
    liveUrl: "https://v0-pallavi-miriyala-portfolio.vercel.app/",
    githubUrl: "https://github.com/example/lua-embedded",
    slug: "lua-embedded-systems-portfolio",
    technologies: ["Lua", "LuaJIT", "LÖVE", "OpenResty", "Wireshark", "World of Warcraft API"],
    featured: false,
    createdAt: "2024-05-05",
  },
  {
    id: "se-26",
    title: "Blockchain Smart Contract Developer Portfolio",
    description:
      "Smart contract development with Solidity, Web3 integration, and decentralized application architecture.",
    shortDescription: "Blockchain smart contract and dApp development",
    image: "/images/p28.png",
    category: "Software Engineering",
    tags: ["Solidity", "Blockchain", "Smart Contracts", "Web3"],
    liveUrl: "https://v0-elsa-portfolio.vercel.app/",
    githubUrl: "https://github.com/example/blockchain-smart-contract",
    slug: "blockchain-smart-contract-developer-portfolio",
    technologies: ["Solidity", "Web3.js", "Truffle", "Hardhat", "MetaMask", "IPFS"],
    featured: false,
    createdAt: "2024-05-10",
  },
  {
    id: "2",
    title: "Testing Portfolio",
    description: "Professional QA and testing portfolio demonstrating expertise in automated testing, test strategy development, and quality assurance processes. Includes comprehensive test frameworks, CI/CD integration, performance testing, and detailed bug tracking systems.",
    shortDescription: "QA and testing portfolio with automation and CI/CD",
    image: "/images/p29.png",
    category: "Quality Assurance",
    tags: ["Selenium", "Jest", "Cypress", "Test Automation"],
    liveUrl: "https://v0-modern-portfolio-website-flame-iota.vercel.app/",
    githubUrl: "https://github.com/example/testing-portfolio",
    slug: "testing-portfolio",
    technologies: ["Selenium", "Jest", "Cypress", "TestNG", "Postman", "Jenkins"],
    featured: true,
    createdAt: "2024-02-20",
  },
  {
    id: "qa-2",
    title: "Mobile Testing Specialist Portfolio",
    description:
      "Specialized mobile application testing across iOS and Android platforms, including device compatibility and performance testing.",
    shortDescription: "Mobile testing specialist for iOS and Android platforms",
    image: "/images/p30.png",
    category: "Quality Assurance",
    tags: ["Mobile Testing", "Appium", "XCUITest", "Espresso"],
    liveUrl: "https://v0-jayden-cole-portfolio.vercel.app/",
    githubUrl: "https://github.com/example/mobile-testing",
    slug: "mobile-testing-specialist-portfolio",
    technologies: ["Appium", "XCUITest", "Espresso", "TestFlight", "Firebase Test Lab", "BrowserStack"],
    featured: false,
    createdAt: "2024-05-15",
  },
  {
    id: "qa-3",
    title: "Performance Testing Engineer Portfolio",
    description:
      "Performance and load testing expertise using JMeter, LoadRunner, and modern performance testing tools.",
    shortDescription: "Performance testing with JMeter and LoadRunner",
    image: "/images/p31.png",
    category: "Quality Assurance",
    tags: ["Performance Testing", "JMeter", "LoadRunner", "Load Testing"],
    liveUrl: "https://v0-portfolio-clone-request-pi.vercel.app/",
    githubUrl: "https://github.com/example/performance-testing",
    slug: "performance-testing-engineer-portfolio",
    technologies: ["JMeter", "LoadRunner", "Gatling", "K6", "New Relic", "Grafana"],
    featured: false,
    createdAt: "2024-05-20",
  },
  {
    id: "qa-4",
    title: "API Testing Automation Portfolio",
    description:
      "API testing automation with REST and GraphQL services, including contract testing and service virtualization.",
    shortDescription: "API testing automation with REST and GraphQL",
    image: "/images/p32.png",
    category: "Quality Assurance",
    tags: ["API Testing", "REST", "GraphQL", "Postman"],
    liveUrl: "https://v0-jahnavi-bethini-blog.vercel.app/",
    githubUrl: "https://github.com/example/api-testing",
    slug: "api-testing-automation-portfolio",
    technologies: ["Postman", "Newman", "REST Assured", "Pact", "WireMock", "Insomnia"],
    featured: false,
    createdAt: "2024-05-25",
  },
  {
    id: "qa-5",
    title: "Security Testing Specialist Portfolio",
    description: "Security testing and penetration testing expertise, focusing on web application security and vulnerability assessment.",
    shortDescription: "Security testing and penetration testing specialist",
    image: "/images/p38.png",
    category: "Quality Assurance",
    tags: ["Security Testing", "Penetration Testing", "OWASP", "Vulnerability Assessment"],
    liveUrl: "https://v0-personal-blog-website-peach.vercel.app/",
    githubUrl: "https://github.com/example/security-testing",
    slug: "security-testing-specialist-portfolio",
    technologies: ["OWASP ZAP", "Burp Suite", "Nessus", "Metasploit", "Nmap", "Wireshark"],
    featured: false,
    createdAt: "2024-05-30",
  },
  {
    id: "hr-1",
    title: "HR Technology Solutions Portfolio",
    description:
      "Human Resources technology solutions including HRIS implementation, employee management systems, and HR analytics platforms.",
    shortDescription: "HR technology solutions and HRIS implementation",
    image: "/images/p33.png",
    category: "Human Resources",
    tags: ["HRIS", "HR Analytics", "Employee Management", "Payroll Systems"],
    liveUrl: "https://v0-luxury-portfolio-website-phi.vercel.app/",
    githubUrl: "https://github.com/example/hr-technology",
    slug: "hr-technology-solutions-portfolio",
    technologies: ["Workday", "BambooHR", "ADP", "Tableau", "Power BI", "SQL Server"],
    featured: false,
    createdAt: "2024-06-01",
  },
  {
    id: "hr-2",
    title: "Talent Acquisition Platform Portfolio",
    description:
      "Talent acquisition and recruitment platform development, including applicant tracking systems and candidate management.",
    shortDescription: "Talent acquisition platform and ATS development",
    image: "/images/p34.png",
    category: "Human Resources",
    tags: ["ATS", "Recruitment", "Talent Acquisition", "Candidate Management"],
    liveUrl: "https://v0-rakesh-portfolio-design.vercel.app/",
    githubUrl: "https://github.com/example/talent-acquisition",
    slug: "talent-acquisition-platform-portfolio",
    technologies: ["React", "Node.js", "MongoDB", "LinkedIn API", "Indeed API", "Greenhouse"],
    featured: false,
    createdAt: "2024-06-05",
  },
  {
    id: "3",
    title: "UI/UX Portfolio",
    description:
      "Creative UI/UX design portfolio showcasing user-centered design principles, interactive prototypes, and modern design systems. Features comprehensive user research, wireframing, visual design, and usability testing with a focus on accessibility and user experience optimization.",
    shortDescription: "Creative UI/UX design with user-centered approach",
    image: "/images/p35.png",
    category: "UI/UX Design",
    tags: ["Figma", "Adobe XD", "Prototyping", "User Research"],
    liveUrl: "https://v0-portfolio-with-images.vercel.app/",
    githubUrl: "https://github.com/example/uiux-portfolio",
    slug: "uiux-portfolio",
    technologies: ["Figma", "Adobe Creative Suite", "Sketch", "InVision", "Principle", "Framer"],
    featured: false,
    createdAt: "2024-03-10",
  },
  {
    id: "ux-2",
    title: "Mobile App UX Designer Portfolio",
    description:
      "Mobile-first UX design specializing in iOS and Android applications, with focus on touch interactions and mobile usability.",
    shortDescription: "Mobile-first UX design for iOS and Android apps",
    image: "/images/p36.png",
    category: "UI/UX Design",
    tags: ["Mobile UX", "iOS Design", "Android Design", "Touch Interactions"],
    liveUrl: "https://v0-portfolio-with-3-d-animation.vercel.app/",
    githubUrl: "https://github.com/example/mobile-ux",
    slug: "mobile-app-ux-designer-portfolio",
    technologies: ["Figma", "Sketch", "Principle", "ProtoPie", "Zeplin", "Marvel"],
    featured: false,
    createdAt: "2024-06-10",
  },
  {
    id: "ux-3",
    title: "Web Accessibility Designer Portfolio",
    description:
      "Web accessibility and inclusive design specialist, ensuring WCAG compliance and universal design principles.",
    shortDescription: "Web accessibility and inclusive design specialist",
    image: "/images/p39.png",
    category: "UI/UX Design",
    tags: ["Accessibility", "WCAG", "Inclusive Design", "Universal Design"],
    liveUrl: "https://v0-tom-cruise-portfolio.vercel.app/",
    githubUrl: "https://github.com/example/accessibility-design",
    slug: "web-accessibility-designer-portfolio",
    technologies: ["Figma", "Axe", "WAVE", "Color Oracle", "Screen Readers", "NVDA"],
    featured: false,
    createdAt: "2024-06-15",
  },
  {
    id: "ux-4",
    title: "E-commerce UX Specialist Portfolio",
    description:
      "E-commerce user experience optimization, conversion rate optimization, and online shopping journey design.",
    shortDescription: "E-commerce UX optimization and conversion design",
    image: "/images/p15.png",
    category: "UI/UX Design",
    tags: ["E-commerce UX", "Conversion Optimization", "Shopping Journey", "A/B Testing"],
    liveUrl: "https://v0-julia-roberts-portfolio-design.vercel.app/",
    githubUrl: "https://github.com/example/ecommerce-ux",
    slug: "ecommerce-ux-specialist-portfolio",
    technologies: ["Figma", "Hotjar", "Google Analytics", "Optimizely", "Unbounce", "Shopify"],
    featured: false,
    createdAt: "2024-06-20",
  },
  {
    id: "ux-5",
    title: "Design Systems Architect Portfolio",
    description:
      "Design systems architecture and component library development, ensuring consistency across digital products.",
    shortDescription: "Design systems architecture and component libraries",
    image: "/images/p16.png",
    category: "UI/UX Design",
    tags: ["Design Systems", "Component Libraries", "Style Guides", "Design Tokens"],
    liveUrl: "https://macaly-l80vvmykjibfbherjj5kg7mz.macaly-app.com/",
    githubUrl: "https://github.com/example/design-systems",
    slug: "design-systems-architect-portfolio",
    technologies: ["Figma", "Storybook", "Abstract", "Zeroheight", "Tokens Studio", "Design Tokens"],
    featured: false,
    createdAt: "2024-06-25",
  },
  {
    id: "ux-6",
    title: "VR/AR Experience Designer Portfolio",
    description:
      "Virtual and Augmented Reality experience design, focusing on immersive interfaces and spatial design.",
    shortDescription: "VR/AR experience design and immersive interfaces",
    image: "/images/p17.png",
    category: "UI/UX Design",
    tags: ["VR Design", "AR Design", "Immersive UX", "Spatial Design"],
    liveUrl: "https://macaly-b4mehws41tiqevk9n84oezvg.macaly-app.com/",
    githubUrl: "https://github.com/example/vr-ar-design",
    slug: "vr-ar-experience-designer-portfolio",
    technologies: ["Unity", "Unreal Engine", "Oculus SDK", "ARKit", "ARCore", "Blender"],
    featured: false,
    createdAt: "2024-06-30",
  },
  {
    id: "4",
    title: "Fullstack Developer Portfolio",
    description:
      "Comprehensive fullstack development portfolio demonstrating end-to-end application development skills. Features modern web technologies, RESTful APIs, database design, and deployment strategies with emphasis on scalable architecture and best practices.",
    shortDescription: "End-to-end fullstack development expertise",
    image: "/images/p18.png",
    category: "Fullstack Development",
    tags: ["React", "Node.js", "MongoDB", "GraphQL"],
    liveUrl: "https://v0-devops-portfolio-design-three.vercel.app/",
    githubUrl: "https://github.com/example/fullstack-portfolio",
    slug: "fullstack-developer-portfolio",
    technologies: ["React", "Node.js", "Express", "MongoDB", "GraphQL", "TypeScript"],
    featured: false,
    createdAt: "2024-04-05",
  },
  {
    id: "fs-2",
    title: "MERN Stack Developer Portfolio",
    description:
      "Full-stack development using MongoDB, Express.js, React, and Node.js with modern development practices.",
    shortDescription: "MERN stack development with modern practices",
    image: "/images/p21.png",
    category: "Fullstack Development",
    tags: ["MERN", "React", "Node.js", "MongoDB"],
    liveUrl: "https://v0-rakesh-portfolio-design.vercel.app/",
    githubUrl: "https://github.com/example/mern-stack",
    slug: "mern-stack-developer-portfolio",
    technologies: ["MongoDB", "Express.js", "React", "Node.js", "JWT", "Mongoose"],
    featured: false,
    createdAt: "2024-07-01",
  },
  {
    id: "fs-3",
    title: "MEAN Stack Developer Portfolio",
    description: "Full-stack development using MongoDB, Express.js, Angular, and Node.js for enterprise applications.",
    shortDescription: "MEAN stack development for enterprise applications",
    image: "/images/p22.png",
    category: "Fullstack Development",
    tags: ["MEAN", "Angular", "Node.js", "MongoDB"],
    liveUrl: "https://v0-dark-theme-portfolio-five.vercel.app/",
    githubUrl: "https://github.com/example/mean-stack",
    slug: "mean-stack-developer-portfolio",
    technologies: ["MongoDB", "Express.js", "Angular", "Node.js", "TypeScript", "RxJS"],
    featured: false,
    createdAt: "2024-07-05",
  },
  {
    id: "fs-4",
    title: "Django React Developer Portfolio",
    description: "Full-stack development combining Django backend with React frontend for robust web applications.",
    shortDescription: "Django React full-stack development",
    image: "/images/p23.png",
    category: "Fullstack Development",
    tags: ["Django", "React", "Python", "REST API"],
    liveUrl: "https://v0-portfolio-clone-request-green.vercel.app/",
    githubUrl: "https://github.com/example/django-react",
    slug: "django-react-developer-portfolio",
    technologies: ["Django", "React", "PostgreSQL", "Django REST Framework", "Redux", "Celery"],
    featured: false,
    createdAt: "2024-07-10",
  },
  {
    id: "fs-5",
    title: "Laravel Vue.js Developer Portfolio",
    description: "Full-stack development using Laravel PHP framework with Vue.js frontend for modern web applications.",
    shortDescription: "Laravel Vue.js full-stack development",
    image: "/images/p24.png",
    category: "Fullstack Development",
    tags: ["Laravel", "Vue.js", "PHP", "MySQL"],
    liveUrl: "https://v0-pallavi-miriyala-portfolio.vercel.app/",
    githubUrl: "https://github.com/example/laravel-vue",
    slug: "laravel-vuejs-developer-portfolio",
    technologies: ["Laravel", "Vue.js", "MySQL", "Eloquent", "Vuex", "Laravel Mix"],
    featured: false,
    createdAt: "2024-07-15",
  },
  {
    id: "fs-6",
    title: "Ruby on Rails React Portfolio",
    description: "Full-stack development combining Ruby on Rails backend with React frontend for rapid development.",
    shortDescription: "Ruby on Rails React full-stack development",
    image: "/images/p25.png",
    category: "Fullstack Development",
    tags: ["Ruby on Rails", "React", "PostgreSQL", "API"],
    liveUrl: "https://v0-elsa-portfolio.vercel.app/",
    githubUrl: "https://github.com/example/rails-react",
    slug: "ruby-on-rails-react-portfolio",
    technologies: ["Ruby on Rails", "React", "PostgreSQL", "Active Record", "Redux", "Sidekiq"],
    featured: false,
    createdAt: "2024-07-20",
  },
  {
    id: "fs-7",
    title: "ASP.NET Core Angular Portfolio",
    description: "Enterprise full-stack development using ASP.NET Core backend with Angular frontend.",
    shortDescription: "ASP.NET Core Angular enterprise development",
    image: "/images/p26.png",
    category: "Fullstack Development",
    tags: ["ASP.NET Core", "Angular", "C#", "SQL Server"],
    liveUrl: "https://v0-personal-blog-website-peach.vercel.app/",
    githubUrl: "https://github.com/example/aspnet-angular",
    slug: "aspnet-core-angular-portfolio",
    technologies: ["ASP.NET Core", "Angular", "Entity Framework", "SQL Server", "SignalR", "Azure"],
    featured: false,
    createdAt: "2024-07-25",
  },
  {
    id: "fs-8",
    title: "Spring Boot React Portfolio",
    description: "Java full-stack development using Spring Boot backend with React frontend for enterprise solutions.",
    shortDescription: "Spring Boot React enterprise solutions",
    image: "/images/p27.png",
    category: "Fullstack Development",
    tags: ["Spring Boot", "React", "Java", "MySQL"],
    liveUrl: "https://v0-luxury-portfolio-website-phi.vercel.app/",
    githubUrl: "https://github.com/example/spring-react",
    slug: "spring-boot-react-portfolio",
    technologies: ["Spring Boot", "React", "MySQL", "Spring Security", "JPA", "Maven"],
    featured: false,
    createdAt: "2024-07-30",
  },
  {
    id: "fs-9",
    title: "Next.js Full-Stack Portfolio",
    description: "Modern full-stack development using Next.js with server-side rendering and API routes.",
    shortDescription: "Next.js full-stack with SSR and API routes",
    image: "/images/p28.png",
    category: "Fullstack Development",
    tags: ["Next.js", "React", "Vercel", "API Routes"],
    liveUrl: "https://v0-portfolio-clone-request-pi.vercel.app/",
    githubUrl: "https://github.com/example/nextjs-fullstack",
    slug: "nextjs-full-stack-portfolio",
    technologies: ["Next.js", "React", "Prisma", "PostgreSQL", "Vercel", "TypeScript"],
    featured: false,
    createdAt: "2024-08-01",
  },
  {
    id: "fs-10",
    title: "Nuxt.js Full-Stack Portfolio",
    description: "Vue.js full-stack development using Nuxt.js framework with universal applications.",
    shortDescription: "Nuxt.js Vue.js full-stack development",
    image: "/images/p29.png",
    category: "Fullstack Development",
    tags: ["Nuxt.js", "Vue.js", "Universal Apps", "SSR"],
    liveUrl: "https://v0-jahnavi-bethini-blog.vercel.app/",
    githubUrl: "https://github.com/example/nuxtjs-fullstack",
    slug: "nuxtjs-full-stack-portfolio",
    technologies: ["Nuxt.js", "Vue.js", "Vuex", "Axios", "Strapi", "MongoDB"],
    featured: false,
    createdAt: "2024-08-05",
  },
  {
    id: "fs-11",
    title: "SvelteKit Full-Stack Portfolio",
    description: "Modern full-stack development using SvelteKit with server-side rendering and optimized performance.",
    shortDescription: "SvelteKit full-stack with optimized performance",
    image: "/images/p30.png",
    category: "Fullstack Development",
    tags: ["SvelteKit", "Svelte", "Performance", "SSR"],
    liveUrl: "https://v0-personal-blog-website-peach.vercel.app/",
    githubUrl: "https://github.com/example/sveltekit-fullstack",
    slug: "sveltekit-full-stack-portfolio",
    technologies: ["SvelteKit", "Svelte", "Vite", "Prisma", "SQLite", "Tailwind CSS"],
    featured: false,
    createdAt: "2024-08-10",
  },
  {
    id: "ai-1",
    title: "Machine Learning Engineer Portfolio",
    description:
      "Machine learning model development, deployment, and optimization using Python, TensorFlow, and cloud platforms.",
    shortDescription: "ML model development and deployment expertise",
    image: "/images/p31.png",
    category: "AI/ML",
    tags: ["Machine Learning", "TensorFlow", "Python", "Model Deployment"],
    liveUrl: "https://v0-portfolio-clone-request-green.vercel.app/",
    githubUrl: "https://github.com/example/ml-engineer",
    slug: "machine-learning-engineer-portfolio",
    technologies: ["Python", "TensorFlow", "Scikit-learn", "Pandas", "NumPy", "AWS SageMaker"],
    featured: false,
    createdAt: "2024-08-15",
  },
  {
    id: "ai-2",
    title: "Deep Learning Specialist Portfolio",
    description: "Deep learning and neural network development using PyTorch, Keras, and advanced AI architectures.",
    shortDescription: "Deep learning and neural network specialist",
    image: "/images/p32.png",
    category: "AI/ML",
    tags: ["Deep Learning", "PyTorch", "Neural Networks", "Computer Vision"],
    liveUrl: "https://v0-portfolio-clone-request-pi.vercel.app/",
    githubUrl: "https://github.com/example/deep-learning",
    slug: "deep-learning-specialist-portfolio",
    technologies: ["PyTorch", "Keras", "OpenCV", "CUDA", "Jupyter", "MLflow"],
    featured: false,
    createdAt: "2024-08-20",
  },
  {
    id: "ai-3",
    title: "Natural Language Processing Portfolio",
    description: "NLP and text analytics solutions using transformers, BERT, and modern language models.",
    shortDescription: "NLP and text analytics with transformers",
    image: "/images/p11.png",
    category: "AI/ML",
    tags: ["NLP", "Transformers", "BERT", "Text Analytics"],
    liveUrl: "https://v0-jahnavi-bethini-blog.vercel.app/",
    githubUrl: "https://github.com/example/nlp",
    slug: "natural-language-processing-portfolio",
    technologies: ["Transformers", "BERT", "spaCy", "NLTK", "Hugging Face", "GPT"],
    featured: false,
    createdAt: "2024-08-25",
  },
  {
    id: "ai-4",
    title: "Computer Vision Engineer Portfolio",
    description: "Computer vision and image processing solutions using OpenCV, YOLO, and deep learning frameworks.",
    shortDescription: "Computer vision and image processing expert",
    image: "/images/p12.png",
    category: "AI/ML",
    tags: ["Computer Vision", "OpenCV", "YOLO", "Image Processing"],
    liveUrl: "https://v0-portfolio-clone-request-pi.vercel.app/",
    githubUrl: "https://github.com/example/computer-vision",
    slug: "computer-vision-engineer-portfolio",
    technologies: ["OpenCV", "YOLO", "TensorFlow", "PIL", "Matplotlib", "Detectron2"],
    featured: false,
    createdAt: "2024-08-30",
  },
  {
    id: "ai-5",
    title: "MLOps Engineer Portfolio",
    description: "MLOps and machine learning pipeline automation, model monitoring, and deployment at scale.",
    shortDescription: "MLOps and ML pipeline automation specialist",
    image: "/images/p13.png",
    category: "AI/ML",
    tags: ["MLOps", "Model Deployment", "Pipeline Automation", "Monitoring"],
    liveUrl: "https://v0-portfolio-clone-request-green.vercel.app/",
    githubUrl: "https://github.com/example/mlops-engineer",
    slug: "mlops-engineer-portfolio",
    technologies: ["Kubeflow", "MLflow", "Docker", "Kubernetes", "Airflow", "Prometheus"],
    featured: false,
    createdAt: "2024-09-01",
  },
  {
    id: "5",
    title: "DevOps Portfolio",
    description:
      "Professional DevOps engineering portfolio showcasing infrastructure automation, CI/CD pipelines, and cloud architecture expertise. Demonstrates containerization, orchestration, monitoring solutions, and infrastructure as code with focus on reliability and scalability.",
    shortDescription: "DevOps engineering with infrastructure automation",
    image: "/images/p14.png",
    category: "DevOps Engineering",
    tags: ["Docker", "Kubernetes", "AWS", "Terraform"],
    liveUrl: "https://v0-devops-portfolio-design-three.vercel.app/",
    githubUrl: "https://github.com/example/devops-portfolio",
    slug: "devops-portfolio",
    technologies: ["Docker", "Kubernetes", "AWS", "Terraform", "Jenkins", "Prometheus"],
    featured: true,
    createdAt: "2024-05-15",
  },
  {
    id: "6",
    title: "Data Science Portfolio",
    description:
      "Advanced data science portfolio featuring machine learning models, data analysis projects, and predictive analytics solutions. Includes comprehensive data visualization, statistical analysis, and AI/ML implementations with real-world applications and insights.",
    shortDescription: "Data science expertise with machine learning focus",
    image: "/images/p20.png",
    category: "Data Science",
    tags: ["Python", "TensorFlow", "Pandas", "Jupyter"],
    liveUrl: "https://v0-portfolio-clone-request-pi.vercel.app/",
    githubUrl: "https://github.com/example/datascience-portfolio",
    slug: "data-science-portfolio",
    technologies: ["Python", "TensorFlow", "Pandas", "Scikit-learn", "Jupyter", "Tableau"],
    featured: false,
    createdAt: "2024-06-10",
  },
  {
    id: "da-1",
    title: "Business Intelligence Analyst Portfolio",
    description:
      "Business intelligence and data analytics using Tableau, Power BI, and SQL for data-driven decision making.",
    shortDescription: "Business intelligence with Tableau and Power BI",
    image: "/images/p36.png",
    category: "Data Analyst",
    tags: ["Business Intelligence", "Tableau", "Power BI", "SQL"],
    liveUrl: "https://v0-portfolio-clone-request-green.vercel.app/",
    githubUrl: "https://github.com/example/bi-analyst",
    slug: "business-intelligence-analyst-portfolio",
    technologies: ["Tableau", "Power BI", "SQL Server", "Excel", "Python", "R"],
    featured: false,
    createdAt: "2024-09-05",
  },
  {
    id: "da-2",
    title: "Financial Data Analyst Portfolio",
    description: "Financial data analysis and modeling using Excel, R, and specialized financial analytics tools.",
    shortDescription: "Financial data analysis and modeling specialist",
    image: "/images/p37.png",
    category: "Data Analyst",
    tags: ["Financial Analysis", "Excel", "R", "Financial Modeling"],
    liveUrl: "https://v0-portfolio-clone-request-pi.vercel.app/",
    githubUrl: "https://github.com/example/financial-analyst",
    slug: "financial-data-analyst-portfolio",
    technologies: ["Excel", "R", "Bloomberg Terminal", "SQL", "VBA", "Python"],
    featured: false,
    createdAt: "2024-09-10",
  },
  {
    id: "da-3",
    title: "Marketing Data Analyst Portfolio",
    description:
      "Marketing analytics and customer insights using Google Analytics, Adobe Analytics, and data visualization tools.",
    shortDescription: "Marketing analytics and customer insights specialist",
    image: "/images/p38.png",
    category: "Data Analyst",
    tags: ["Marketing Analytics", "Google Analytics", "Customer Insights", "A/B Testing"],
    liveUrl: "https://v0-jahnavi-bethini-blog.vercel.app/",
    githubUrl: "https://github.com/example/marketing-analyst",
    slug: "marketing-data-analyst-portfolio",
    technologies: ["Google Analytics", "Adobe Analytics", "Tableau", "SQL", "Python", "Google Tag Manager"],
    featured: false,
    createdAt: "2024-09-15",
  },
]

export const servicesData: Service[] = [
  {
    id: "1",
    title: "Software Engineering",
    description:
      "Custom software solutions built with modern technologies, clean architecture, and scalable design patterns.",
    icon: "💻",
    price: "Starting at $8,000",
  },
  {
    id: "2",
    title: "Quality Assurance & Testing",
    description:
      "Comprehensive testing strategies including automated testing, performance testing, and quality assurance processes.",
    icon: "🧪",
    price: "Starting at $4,000",
  },
  {
    id: "3",
    title: "UI/UX Design",
    description:
      "User-centered design solutions that create engaging and intuitive digital experiences with modern aesthetics.",
    icon: "🎨",
    price: "Starting at $5,000",
  },
  {
    id: "4",
    title: "Fullstack Development",
    description: "End-to-end web application development using cutting-edge frontend and backend technologies.",
    icon: "🌐",
    price: "Starting at $10,000",
  },
  {
    id: "5",
    title: "DevOps & Infrastructure",
    description: "Cloud infrastructure automation, CI/CD pipelines, and scalable deployment solutions.",
    icon: "⚙️",
    price: "Starting at $6,000",
  },
  {
    id: "6",
    title: "Data Science & Analytics",
    description: "Advanced data analysis, machine learning models, and predictive analytics solutions.",
    icon: "📊",
    price: "Starting at $12,000",
  },
]

export const teamData: TeamMember[] = [
  {
    id: "1",
    name: "Banti M",
    role: "Fullstack Developer",
    image: "/a3.jpg",
    bio: "Full-stack engineer with more years experience in scalable system design and modern development practices.",
  },
  {
    id: "2",
    name: "Manideep Reddy Sripathi",
    role: "Software Engineer/Pilot",
    image: "/a4.jpg",
    bio: "Cloud infrastructure specialist focusing on automation, containerization, and CI/CD pipeline optimization.",
  },
  {
    id: "3",
    name: "Vishwa Sai Gaddi",
    role: "Sales Executive/Pilot",
    image: "/a6.jpg",
    bio: "Creative designer passionate about user experience and modern design systems with accessibility focus.",
  },
  {
    id: "4",
    name: "Pallavi Miriyala",
    role: "Software Engineer/Tester",
    image: "/a5.jpg",
    bio: "Quality assurance expert specializing in test automation, performance testing, and quality processes.",
  },
]

export const testimonialsData: Testimonial[] = [
  {
    id: "1",
    name: "John Smith",
    role: "CTO",
    company: "TechStartup Inc",
    content:
      "Their software engineering expertise helped us build a scalable platform that handles millions of users seamlessly.",
    avatar: "/placeholder.svg?height=60&width=60",
  },
  {
    id: "2",
    name: "Lisa Wang",
    role: "Product Manager",
    company: "InnovateApp",
    content:
      "The UI/UX design work transformed our user experience completely. Our engagement rates increased by 300%.",
    avatar: "/placeholder.svg?height=60&width=60",
  },
  {
    id: "3",
    name: "Robert Brown",
    role: "Engineering Director",
    company: "CloudTech Solutions",
    content: "Outstanding DevOps implementation. Our deployment time reduced from hours to minutes with zero downtime.",
    avatar: "/placeholder.svg?height=60&width=60",
  },
]

export const mockMessages: ContactMessage[] = [
  {
    id: "1",
    name: "Alice Cooper",
    email: "alice@techstartup.com",
    message:
      "Interested in your software engineering services for our fintech platform. Can we schedule a technical discussion?",
    createdAt: "2024-01-15T10:30:00Z",
    status: "new",
  },
  {
    id: "2",
    name: "Bob Wilson",
    email: "bob@designstudio.com",
    message: "Looking for UI/UX design expertise for our mobile app redesign project. What's your process?",
    createdAt: "2024-01-14T15:45:00Z",
    status: "read",
  },
]

export const dashboardStats: DashboardStats = {
  totalPortfolios: portfolioData.length,
  totalMessages: mockMessages.length,
  totalViews: 1250,
  totalInquiries: 45,
}
